language: node_js
node_js: lts/carbon
cache:
  directories:
    - node_modules
    - .tmp
    - ~/.npm
notifications:
  email: false
before_install:
  - git fetch origin --tags

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^v\d+\.\d+\.\d+$
  - name: release
    if: branch = master AND fork = false AND type IN (push, api)

jobs:
  include:
    -
      stage: test
      script:
        - npm run lint
        - npm run flow
        - npm run test-ci
      after_success:
        - npm install --no-save coveralls
        # Report coverage to coveralls.io
        - cat ./__coverage__/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        - rm -fr ./__coverage__

    -
      stage: release
      script:
        - npm run semantic-release
